import Head from 'next/head'
import Image from 'next/image'
import Sidenav from '../components/Sidenav'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
<<<<<<< HEAD
        <title>QuickQ</title>
=======
        <title>Create Next App- srp 3rd commit testing</title>
>>>>>>> a3b3076754bfb86ba6f292e22df51f9d987caf36
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidenav />
      <main className={styles.main}>
        

      </main>
    </div>
  )
}
