import Head from 'next/head'
import Image from 'next/image'
import Sidenav from '../components/Sidenav'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>QuickQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidenav />
      <main className={styles.main}>
        

      </main>
    </div>
  )
}
